# Generated by Django 5.0.4 on 2024-05-03 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_collections_card_alter_collections_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansions',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.cards', verbose_name='User collection owner'),
        ),
    ]
