# Generated by Django 5.0.4 on 2024-05-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_expansions_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expansions',
            name='card',
        ),
        migrations.AddField(
            model_name='cards',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.expansions', verbose_name='Expansion card'),
        ),
    ]
