# Generated by Django 5.0.4 on 2024-05-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_cards_deck_remove_decks_heroes_decks_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='is_legendary',
            field=models.BooleanField(default=False),
        ),
    ]
