# Generated by Django 5.0.4 on 2024-05-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_cards_is_legendary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='card_ability',
        ),
    ]
