# Generated by Django 5.0.4 on 2024-05-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_collections_card_collections_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.bases', verbose_name='Main Base deck'),
        ),
    ]
