# Generated by Django 5.0.4 on 2024-05-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_decks_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='decks',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.collections', verbose_name='Collection Owner deck'),
        ),
    ]
