# Generated by Django 5.0.4 on 2024-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_decks_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decks',
            name='collection',
        ),
        migrations.AddField(
            model_name='collections',
            name='decks',
            field=models.ManyToManyField(blank=True, null=True, to='backend.decks'),
        ),
    ]
